Some tabs snuck in here. You're a monster, vim

diff --git a/buildroot/board/meraki/ms200/overlay/etc/init.d/S08kmods b/buildroot/board/meraki/ms200/overlay/etc/init.d/S08kmods
--- a/buildroot/board/meraki/ms200/overlay/etc/init.d/S08kmods
+++ b/buildroot/board/meraki/ms200/overlay/etc/init.d/S08kmods
@@ -118,42 +118,42 @@ fwcutter() {
     # check that the kernel modules exist
     if [ ! -d /lib/modules/${mod_dir} ]; then
         # deploy fwcutter!
-	command -v find_hdr
-	if [ $? -eq 0 ]; then
+        command -v find_hdr
+        if [ $? -eq 0 ]; then
             # store current kernel version
-	    KVER=$(uname -r | awk -F'-' '{print $1}')
-	    export KVER
+            KVER=$(uname -r | awk -F'-' '{print $1}')
+            export KVER
             # find the mtd partition
-	    fw_regions="part1 part2"
-	    for part in $fw_regions; do
-	        MTD_PART=$(grep ${part} /proc/mtd | awk -F':' '{print $1}' | grep -o '[[:digit:]]*')
-		dd if=/dev/mtdblock${MTD_PART} of=/tmp/${part}.bin bs=1M
-		RD_OFFSET=$(find_hdr -g /tmp/${part}.bin)
-		# no header, skip
-		if [ $RD_OFFSET -lt 0 ]; then
+            fw_regions="part1 part2"
+            for part in $fw_regions; do
+                MTD_PART=$(grep ${part} /proc/mtd | awk -F':' '{print $1}' | grep -o '[[:digit:]]*')
+                dd if=/dev/mtdblock${MTD_PART} of=/tmp/${part}.bin bs=1M
+                RD_OFFSET=$(find_hdr -g /tmp/${part}.bin)
+                # no header, skip
+                if [ $RD_OFFSET -lt 0 ]; then
                     rm /tmp/${part}.bin
-		else
+                else
                     BLOCK_SIZE=$(largest_blocksize $RD_OFFSET)
                     # found GZIP header, it's at RD_OFFSET
-		    dd if=/tmp/${part}.bin of=/tmp/initrd-${part}.gz bs=$BLOCK_SIZE skip=$(($RD_OFFSET/$BLOCK_SIZE))
-		    rm /tmp/${part}.bin
-		    # extract the kernel modules from initrd.gz
-		    cd /tmp && gzip -dc /tmp/initrd-${part}.gz | cpio -idu lib/modules/*.ko lib/modules/${mod_dir}
+                    dd if=/tmp/${part}.bin of=/tmp/initrd-${part}.gz bs=$BLOCK_SIZE skip=$(($RD_OFFSET/$BLOCK_SIZE))
+                    rm /tmp/${part}.bin
+                    # extract the kernel modules from initrd.gz
+                    cd /tmp && gzip -dc /tmp/initrd-${part}.gz | cpio -idu lib/modules/*.ko lib/modules/${mod_dir}
                     rm /tmp/initrd-${part}.gz
-		    # check the module version
-		    RD_KVER=$(strings /tmp/lib/modules/${mod_dir}/vtss_core.ko | grep 'vermagic=' | awk -F'=' '{print $2}' | awk -F'-' '{print $1}')
-		    if [ "$RD_KVER" != "$KVER" ]; then
+                    # check the module version
+                    RD_KVER=$(strings /tmp/lib/modules/${mod_dir}/vtss_core.ko | grep 'vermagic=' | awk -F'=' '{print $2}' | awk -F'-' '{print $1}')
+                    if [ "$RD_KVER" != "$KVER" ]; then
                         echo "$part contains modules for $RD_KVER, but we booted $KVER"
-			# clean up modules
-			rm -rf /tmp/lib
+                        # clean up modules
+                        rm -rf /tmp/lib/modules
                     else
                         echo "Found kernel modules in $part"
-	                export MOD_PATH=/tmp/lib/modules
+                        export MOD_PATH=/tmp/lib/modules
                         load_modules
-			# we loaded the modules, bail
-			return
+                        # we loaded the modules, bail
+                        return
                     fi
-	        fi
+                fi
             done
             echo "Couldn't find kernel modules for $KVER"
         else
@@ -178,6 +178,7 @@ stop() {
         modprobe -r -f $mod
         if [ $? -ne 0 ]; then
             echo "Error removing '${mod}.ko'" > /dev/kmsg
+            return
         fi
     done
 }
